timezone: Europe/Dublin

# Site-wide settings
author:
  name: AmyMialee
  email: contact@amymialee.dev
title: AmyMialee's Hideout
email: contact@amymialee.dev
url: "https://amymialee.dev"
description: >
  AmyMialee's website and portfolio website.
  This website contains information about Amy's Projects, Game Development, Minecraft Mods and others.

# Build settings
remote_theme: "jekyll/minima@bf9ef98"
minima:
  hide_site_feed_link: true
  skin: dark
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap